# Generated by Django 3.2.16 on 2022-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_ziptocoords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziptocoords',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ziptocoords',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='ziptocoords',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='ziptocoords',
            name='name',
        ),
        migrations.AlterField(
            model_name='ziptocoords',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
